name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run unit tests with Jest
      - name: Run Unit Tests
        run: npm test

      # Generate Jest coverage report
      - name: Generate Test Coverage
        run: npm test -- --coverage

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::471112631123:role/OIDCStack-Role-4ZOjnedmQvXE
          aws-region: us-east-1

      - name: Deploy to AWS
        run: |
          aws s3 ls

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Deploy logic (example placeholder)
      - name: Deploy
        run: echo "Deploying the application..."
