name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Permite obtener el token OIDC
      contents: read  # Permite leer el repositorio (si es necesario)
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run unit tests with Jest
      - name: Run Unit Tests
        run: npm test

      # Generate Jest coverage report
      - name: Generate Test Coverage
        run: npm test -- --coverage


      - name: Install AWS CLI
        run: |
          aws --version
          # aws configure set aws_access_key_id "AKIAI44QH8DHBEXAMPLE" --profile user2 && aws configure set aws_secret_access_key "je7MtGbClwBF/2Zp9Utk/h3yCo8nvbEXAMPLEKEY" --profile user2 && aws configure set region "us-east-1" --profile user2 && aws configure set output "text" --profile user2

          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_REGION=us-east-1
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile && aws configure set aws_secret_access_key "$AWS_ACCESS_KEY_SECRET" && aws configure set region "$AWS_REGION" && aws configure set output "json"

      - name: Deploy to AWS
        run: |
          aws s3 ls

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Deploy logic (example placeholder)
      - name: Deploy
        run: echo "Deploying the application..."
