name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Run unit tests with Jest
      - name: Run Unit Tests
        run: |
          ls
          pwd
          npm test

      # Generate Jest coverage report
      - name: Generate Test Coverage
        run: npm test -- --coverage

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests
      - name: Run Tests
        run: npm test

      # Build the project
      - name: Build Project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Deploy logic (example placeholder)
      - name: Deploy
        run: echo "Deploying the application..."
