name: Rollback

on:
  push:
    branches:
      - main
    paths:
      - env.rollback
      - .github/workflows/rollback.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Edit manifest
        run: |
          set -a
          source env.rollback
          set +a
          sed -i "s|\(image: .*:\)latest|\1$IMAGE_TAG|" k8s/app.yaml

      - name: Confing EKS
        run: |
          aws eks update-kubeconfig --name challenge-eks --region $AWS_REGION

      - name: Deploy EKS
        run: |
          echo Pushing the Docker image...
          kubectl apply -f k8s/app.yaml